spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create #create1
    properties:
      hibernate:
        format_sql: true
  #        dialect: org.hibernate.dialect.MariaDBDialect

  devtools:
    livereload:
      enabled: true
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER



logging:
#  file:
#    name: logfiles
#    max-size: 500MB
#    max-history: 10
  level:
    com.hwan.delivery: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#path:
#  local: /home/ec2-user/app/step2/img